% Create a horn antenna
% Generated by MATLAB(R) 9.14 and Antenna Toolbox 5.4.
% Generated on: 18-Nov-2023 15:09:56

clear;
close all;


%%
FreqRanges = [20, 15, 10, 5, 2, 1]*1e9;

%% Antenna Properties 

antennaObject = hornConicalCorrugated;
% Show

Radius = 0.012;
WaveguideHeight = 0.03;
FirstCorrugateDistance = 0.006;
Pitch = 0.0036;
CorrugateWidth = 0.0014;
CorrugateDepth = 0.004;
ConeHeight = 0.0348;
ApertureRadius = 0.018;

antennaObject.Radius = Radius;
antennaObject.WaveguideHeight = WaveguideHeight;
antennaObject.FirstCorrugateDistance = FirstCorrugateDistance;
antennaObject.Pitch = Pitch;
antennaObject.CorrugateWidth = CorrugateWidth;
antennaObject.CorrugateDepth = CorrugateDepth;
antennaObject.ConeHeight = ConeHeight;
antennaObject.ApertureRadius = ApertureRadius;

figure;
show(antennaObject)
savefig('mainFigure.fig')

%% Antenna Analysis 
% Define plot frequency 
% plotFrequency = 15*1e9;
% Define frequency range
for i = FreqRanges
    cd(string(i/1e9))
    freqRange = (0.9*i:(1.1*i - 0.9*i)/60:1.1*i);
    refImpedance = 50;
    figure;
    s = sparameters(antennaObject, freqRange, refImpedance); 
    %rfplot
    rfplot(s)
    savefig("rfPlot" + i/1e9 + ".fig")
    figure;
    %pattern
    pattern(antennaObject, i)
    savefig("3dpattern" + i/1e9 + ".fig")
    % azimuth
    figure;
    patternAzimuth(antennaObject, i, 0, 'Azimuth', 0:5:360)
    savefig("patternAzimuth" + i/1e9 + ".fig")
    % elevation
    figure;
    patternElevation(antennaObject, i,0,'Elevation',0:5:360)
    savefig("patternElevation" + i/1e9 + ".fig")
    % impedance
    figure;
    impedance(antennaObject, freqRange)
    savefig("patternElevation" + i/1e9 + ".fig")
    save("ws" + i/1e9)
    cd ..
end